In [1]:
from importlib import reload

In [2]:
import load_data

Loading up the load data and exploring the columns

In [3]:
loans = load_data.read_zipped_csv('./lending-club-loan-data.zip', 'loan.csv')
print(loans.columns)

/opt/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2802: DtypeWarning: Columns (19,55) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):


Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'emp_title',
       'emp_length', 'home_ownership', 'annual_inc', 'verification_status',
       'issue_d', 'loan_status', 'pymnt_plan', 'url', 'desc', 'purpose',
       'title', 'zip_code', 'addr_state', 'dti', 'delinq_2yrs',
       'earliest_cr_line', 'inq_last_6mths', 'mths_since_last_delinq',
       'mths_since_last_record', 'open_acc', 'pub_rec', 'revol_bal',
       'revol_util', 'total_acc', 'initial_list_status', 'out_prncp',
       'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp',
       'total_rec_int', 'total_rec_late_fee', 'recoveries',
       'collection_recovery_fee', 'last_pymnt_d', 'last_pymnt_amnt',
       'next_pymnt_d', 'last_credit_pull_d', 'collections_12_mths_ex_med',
       'mths_since_last_major_derog', 'policy_code', 'application_type',
       'annual_inc_joint', 'dti_joint', 'verification_status_joint',
    

Now, create a table model with all available columns.

In [4]:
import table_model
reload(table_model)

feature_columns = {
    'loan_amnt': table_model.NumericColumn(),
    'funded_amnt': table_model.NumericColumn(),
    'funded_amnt_inv': table_model.NumericColumn(),
    'term': table_model.CategoricalColumn(),
    'int_rate': table_model.PercentageColumn(),
    'installment': table_model.NumericColumn(),
    'grade': table_model.CategoricalColumn(),
    'sub_grade': table_model.CategoricalColumn(),
    'emp_length': table_model.CategoricalColumn(),
    'addr_state': table_model.CategoricalColumn(),
    'home_ownership': table_model.CategoricalColumn(),
    'annual_inc': table_model.NumericColumn(),
    'annual_inc_joint': table_model.NumericColumn(),
    'dti': table_model.NumericColumn(),
    'dti_joint': table_model.NumericColumn(),
    'open_acc': table_model.NumericColumn(),
    'total_acc': table_model.NumericColumn(),
    'pub_rec': table_model.NumericColumn(),
    'tot_coll_amt': table_model.NumericColumn(),
    'total_bal_il': table_model.NumericColumn(),
    'tot_cur_bal': table_model.NumericColumn(),
    'revol_bal': table_model.NumericColumn(),
    'revol_util': table_model.PercentageColumn(),
    'mths_since_last_delinq': table_model.NumericColumn(),
    'mths_since_last_record': table_model.NumericColumn(),
    'mths_since_last_major_derog': table_model.NumericColumn(),
    'inq_fi': table_model.NumericColumn(),
    'inq_last_12m': table_model.NumericColumn(),
    # and the output
    'loan_status': table_model.OutputLabelColumn(),
}

loan_model = table_model.TableModel(feature_columns, 'loan_status')
filtered = loans.loc[loans.loan_status.isin(['Current', 'Default'])]
loan_model.fit(filtered)
x, y = loan_model.transform(filtered)

Using TensorFlow backend.
/opt/conda/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [5]:
print(x)

[[-1.44078188 -1.44083979 -1.44067283 ..., -0.52961698 -0.08135268
  -0.07797889]
 [-0.97000671 -0.96998009 -0.96960402 ..., -0.52961698 -0.08135268
  -0.07797889]
 [-0.61692533 -0.61683532 -0.6192466  ..., -0.52961698 -0.08135268
  -0.07797889]
 ..., 
 [-0.26384396 -0.26369055 -0.26300081 ..., -0.52961698 -0.08135268
  -0.07797889]
 [-0.38153775 -0.38140548 -0.38076802 ...,  0.42802006 -0.08135268
  -0.07797889]
 [ 0.56001258  0.56031391  0.5613696  ..., -0.52961698 -0.08135268
  -0.07797889]]


In [6]:
print(y)

[0 0 0 ..., 0 0 0]


In [7]:
import keras

model = keras.models.Sequential()
y_one_hot = keras.utils.to_categorical(y)
# logistic regression is a one layer model
model.add(keras.layers.Dense(y_one_hot.shape[1], activation='sigmoid', input_dim=x.shape[1]))
model.compile(optimizer='adam', loss='categorical_crossentropy')
model.fit(x, y_one_hot, epochs=2, verbose=1)

Epoch 1/2
602998/602998 [==============================] - 19s 32us/step - loss: 0.0243
Epoch 2/2
602998/602998 [==============================] - 18s 30us/step - loss: 0.0146


In [8]:
predictions = model.predict_classes(x)

In [9]:
import sklearn.metrics
print(sklearn.metrics.accuracy_score(y, predictions))

0.997817571534


Looks good -- but there is probably a catch here, looking at the balance of classes, far more loans are 'Current' than 'Default', so our model probaly just learned to guess 'Current'.

In [10]:
import numpy as np
labels, counts = np.unique(y, return_counts=True)
print(labels, counts)

[0 1] [601779   1219]


In [11]:
print(1 - (counts[1] / counts[0]))

0.997974339417


So -- these highly imbalanced classes will make it hard to predict 'Default', let's see it that was the case.

In [ ]:
print(np.unique(predictions, return_counts=True))

In [12]:
print(sklearn.metrics.classification_report(y, predictions, target_names=loan_model.classes))

             precision    recall  f1-score   support

    Current       1.00      1.00      1.00    601779
    Default       0.00      0.00      0.00      1219

avg / total       1.00      1.00      1.00    602998



So -- clearly the model isn't actually very useful, even though it is accurate! 
Real data often needs to predict relatively rare events.

In [13]:
reload(table_model)

logistic_regression_model = table_model.KerasLogisticRegressionModel()
logistic_regression_model.fit(x, y)

Epoch 1/10
602998/602998 [==============================] - 18s 29us/step - loss: 1.3324
Epoch 2/10
602998/602998 [==============================] - 17s 28us/step - loss: 1.2804
Epoch 3/10
602998/602998 [==============================] - 17s 29us/step - loss: 1.2709
Epoch 4/10
602998/602998 [==============================] - 19s 32us/step - loss: 1.2608
Epoch 5/10
602998/602998 [==============================] - 19s 31us/step - loss: 1.2653
Epoch 6/10
602998/602998 [==============================] - 19s 31us/step - loss: 1.2769


KerasLogisticRegressionModel(verbose=1)

In [14]:
balanced_predictions = logistic_regression_model.predict(x)

In [15]:
print(sklearn.metrics.accuracy_score(y, balanced_predictions))

0.616988779399


In [16]:
print(np.unique(balanced_predictions, return_counts=True))

(array([0, 1]), array([371568, 231430]))


So - the accuracy went down, but the model is at leasty tring to predict 'Default'

In [17]:
print(sklearn.metrics.classification_report(y, balanced_predictions, target_names=loan_model.classes))

             precision    recall  f1-score   support

    Current       1.00      0.62      0.76    601779
    Default       0.00      0.69      0.01      1219

avg / total       1.00      0.62      0.76    602998



Now - to try a deep learning model

In [ ]:
reload(table_model)
deep_model = table_model.KerasDeepClassifierModel()
deep_model.fit(x, y)

Epoch 1/16
602998/602998 [==============================] - 102s 169us/step - loss: 1.4741
Epoch 2/16
602998/602998 [==============================] - 98s 163us/step - loss: 1.3166
Epoch 3/16
103104/602998 [====>.........................] - ETA: 1:33 - loss: 1.2291

In [19]:
deep_predictions = deep_model.predict(x)

In [20]:
print(sklearn.metrics.accuracy_score(y, deep_predictions))

0.739778573063


In [21]:
print(np.unique(deep_predictions, return_counts=True))

(array([0, 1]), array([445578, 157420]))


In [22]:
print(sklearn.metrics.classification_report(y, deep_predictions, target_names=loan_model.classes))

             precision    recall  f1-score   support

    Current       1.00      0.74      0.85    601779
    Default       0.01      0.71      0.01      1219

avg / total       1.00      0.74      0.85    602998



And now -- combining both of these techniques in Wide + Deep models

In [ ]:
reload(table_model)
deep_model = table_model.KerasWideAndDeepClassifierModel()
deep_model.fit(x, y)

In [25]:
wd_predictions = grid.predict(x)

In [26]:
print(sklearn.metrics.accuracy_score(y, wd_predictions))

0.997978434423


In [27]:
print(np.unique(wd_predictions, return_counts=True))

(array([0]), array([602998]))


In [28]:
print(sklearn.metrics.classification_report(y, wd_predictions, target_names=loan_model.classes))

             precision    recall  f1-score   support

    Current       1.00      1.00      1.00    601779
    Default       0.00      0.00      0.00      1219

avg / total       1.00      1.00      1.00    602998



/opt/conda/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
